Assessment/Assessment/Models/OrderModel.cs
using DB_Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Assessment.Models
{
    public class OrderModel
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float Discount { get; set; }

        public virtual OrderModel Order { get; set; }
        public virtual Product Product { get; set; }
    }
}

Assessment/Assessment/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Assessment/Assessment/Controllers/OrderDetailsController.cs
using Assessment.Models;
using DB_Logic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assessment.Controllers
{
    public class OrderDetailsController : Controller
    {
        public static NorthwindEntities obj = new NorthwindEntities();
        public static IEnumerable<Order_Detail> or = obj.Order_Details;
        public static List<OrderModel> orList = new List<OrderModel>();
        // GET: OrderDetails
        public ActionResult Index()
        {
            
            foreach (var item in or)
            {
                orList.Add(new OrderModel { OrderID = item.OrderID, ProductID = item.ProductID, UnitPrice = item.UnitPrice, Quantity = item.Quantity, Discount = item.Discount});
            }


            return View(orList);

        }
        //----------------------------------------Task2----------------------------------------------------
        public ActionResult TotalOrderValue()
        {
            // Fetch all order details
            var orderDetails = obj.Order_Details.ToList();

            // Calculate total order value (Qty * UnitPrice)
            decimal totalValue = orderDetails.Sum(o => o.Quantity * o.UnitPrice);

            // Store result in ViewBag
            ViewBag.TotalOrderValue = totalValue;

            return View();
            
        }
        //---------------------------------Task 3---------------------------------------------------
        public ActionResult ProductsSold()
        {

            return View();
        }

        [HttpPost]
        public ActionResult ProductsSoldById(int id)
        {
           

            List<OrderModel> byId = orList.Where(i => i.ProductID == id).ToList();

            double ans = byId.Any() ? byId.Average(i => i.Quantity) : 0;

            ViewBag.avg = ans;
            return View(byId);
        }
        //------------------------------------Task 4---------------------------------------------------
        public ActionResult ProductsByOrderId()
        {

            return View();
        }

        [HttpPost]
        public ActionResult GetProductsByOrderId(int id)
        {


            List<OrderModel> byId = orList.FindAll(i => i.OrderID == id).ToList();

            return View(byId);
        }
        // GET: OrderDetails/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: OrderDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderDetails/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderDetails/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderDetails/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderDetails/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderDetails/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assessment/Assessment/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Assessment/Assessment/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assessment/Assessment/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Assessment/Assessment/Views/OrderDetails/GetProductsByOrderId.cshtml
@model IEnumerable<Assessment.Models.OrderModel>

@{
    ViewBag.Title = "GetProductsByOrderId";
}

<h2>GetProductsByOrderId</h2>

<p>
    @Html.ActionLink("Go Back", "ProductsByOrderId")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>


}
    
    

    @Html.ActionLink("ProductsByOrderId", "ProductsByOrderId", new { /* id=item.PrimaryKey */ })

    

</table>

Assessment/Assessment/Views/OrderDetails/Index.cshtml
@model IEnumerable<Assessment.Models.OrderModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>




<p>
    @Html.ActionLink("Total of Order", "TotalOrderValue")
</p>


<p>
    @Html.ActionLink("Find avg of Sold Product", "ProductsSold")
</p>


<p>
    @Html.ActionLink("Find the Product by Order Id", "ProductsByOrderId")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

</table>

Assessment/Assessment/Views/OrderDetails/ProductsByOrderId.cshtml
@{
    ViewBag.Title = "ProductsByOrderId";
}

<p>
    @Html.ActionLink("Go Back", "Index")
</p>

<div class="container mt-4">
    <h2 class="text-primary mb-4">Products By OrderId</h2>

    @using (Html.BeginForm("GetProductsByOrderId", "OrderDetails", FormMethod.Post, new { @class = "card p-4 shadow-sm" }))
    {
        <div class="mb-3">
            @Html.Label("Enter the order ID", new { @class = "form-label fw-bold" })
            @Html.TextBox("id", null, new { @class = "form-control", placeholder = "Enter Order ID..." })
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    }
</div>
@Html.ActionLink("Index", "Index", new { /* id=item.PrimaryKey */ })

Assessment/Assessment/Views/OrderDetails/ProductsSold.cshtml
@{
    ViewBag.Title = "Products Sold";
}
<p>
    @Html.ActionLink("Go Back", "Index")
</p>
<div class="container mt-4">
    <h2 class="text-primary mb-4">Products Sold</h2>

    @using (Html.BeginForm("ProductsSoldById", "OrderDetails", FormMethod.Post, new { @class = "card p-4 shadow-sm" }))
    {
        <div class="mb-3">
            @Html.Label("Enter the Product ID", new { @class = "form-label fw-bold" })
            @Html.TextBox("id", null, new { @class = "form-control", placeholder = "Enter Product ID" })
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    }
</div>

Assessment/Assessment/Views/OrderDetails/ProductsSoldById.cshtml
@model IEnumerable<Assessment.Models.OrderModel>

@{
    ViewBag.Title = "ProductsSoldById";
}

<h2>ProductsSoldById</h2>

<p>
    @Html.ActionLink("Go Back", "ProductsSold")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Discount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Discount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}
    

    <h2>Average of Quantities  :</h2>

    <h2>@ViewBag.avg</h2>

    <br />
    <div>
        @Html.ActionLink("Index", "Index")
    </div>

</table>

Assessment/Assessment/Views/OrderDetails/TotalOrderValue.cshtml
@{
    ViewBag.Title = "TotalOrderValue";
}
<p>
    @Html.ActionLink("Go Back", "Index")
</p>

<h2>TotalOrderValue</h2>
<h2>Total value of all orders=Rs @ViewBag.TotalOrderValue </h2>

Assessment/Assessment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>